### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by angelblue05** [MediaBrowser/MediaBrowser.Kodi#110]
The token is not always returned correctly in Kodi.
http://mediabrowser.tv/community/index.php?/topic/18888-30553926606-incorrect-usernamepassword-in-kodi/

**Comment by jluce50** [comment]
Just in case it's helpful, this seems to happen every other time Kodi is launched. I'll get the error, restart Kodi, and it's fine. Then the next time it start I get the error again.

**Comment by angelblue05** [comment]
Fixed in 0.9.812. Case closed.
